import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="topSegment my-8 flex flex-row items-center justify-between">
          <div className="branding">
            <h3 className="text-2xl text-white fRegular" >The</h3>
            <h1 className="text-7xl text-white font-bold fMedium" >MClub</h1>
            <p className="text-white text-xl font-light fLight " >Join the biggest club of movie freaks </p>
          </div>
          <div className="searchDom relative w-fit">
            <input type="text" placeholder="Search" className="text-white bg-[#07171D] border-[#053B4B] border-2 px-5 py-2 rounded-lg fRegular outline-none" />
            <svg className="absolute top-[1rem] right-5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="grey" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </div>
        </div> */}
        {children}
      </body>
    </html>
  );
}
